### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by theGolyo** [Sawamara/space_shooter_pixi_ts#1]
Hi!
Thanks for making the game, even though it is simple, I really enjoyed playing it! :)
I'm curious if you could make some small improvements to the shape of the code:

I'd like you to modernize this repo, add a package.json and import pixi and its types through installed node modules. We will also need a bundler - webpack/ts-loader seems to be the most fashionable these days. This way we could target es5 as well, and using typescript's bundler would not be needed anymore. TSLint would also be an excellent addition, you can pick whatever ruleset you want.

There are also a few unused files that should be deleted.

Please feel free to take your time, there is no deadline on this one - nor is it necessary to move forward :) 

Marton

**Comment by Sawamara** [comment]
Hi, and thank you! : )

I considered building it with Webpack from the start, but since the specification said not to use anything other than PIXI and Typescript, even including the pixi.d.ts files gave me a bit of a pause :D 

I will update the repository soon with the requested additions and a structure slightly more suited to modern development standards.

**Comment by Sawamara** [comment]
Update: added the requested additions, including tslint, webpack and ts-loader. Now, after cloning the repo, run npm install, then npm run start, and it should be ready to go.

**Comment by theGolyo** [comment]
thanks for the super quick updates! :)
